name: Nexus
version: '${project.version}'
main: fr.heneria.nexus.NexusPlugin
api-version: '1.21'
authors: [GordoxGit]
description: Mode de jeu PvP compétitif par équipes avec système de classes, économie et progression

depend: []

softdepend:
  - Vault
  - LuckPerms
  - WorldEdit
  - FastAsyncWorldEdit
  - PlaceholderAPI

load: POSTWORLD

commands:
  nexus:
    description: Commande principale du plugin Nexus
    usage: /<command> [args]
    aliases: [nx]
    permission: nexus.use
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande."

permissions:
  nexus.use:
    description: Permission de base pour utiliser le plugin
    default: true

  nexus.admin:
    description: Accès complet aux commandes d'administration
    default: op
    children:
      nexus.use: true

  nexus.vip:
    description: Avantages VIP (priorité file, cosmétiques)
    default: false

  nexus.play:
    description: Permission de jouer aux parties Nexus
    default: true
