name: Nexus
version: ${project.version}
main: com.heneria.nexus.NexusPlugin
softdepend: [Vault, PlaceholderAPI, LuckPerms]
description: Plugin noyau Nexus pour PaperMC.
authors: [Heneria]
api-version: '1.21'
load: POSTWORLD
commands:
  nexus:
    description: Commande principale du plugin Nexus.
    usage: /<command> help|reload|dump|budget [arena]|holo|admin
    permission: nexus.use
    aliases: [nx]
permissions:
  nexus.use:
    description: Accéder aux commandes publiques de Nexus.
    default: true
  nexus.admin.reload:
    description: Recharger la configuration Nexus.
    default: op
  nexus.admin.dump:
    description: Afficher un dump d'état Nexus.
    default: op
  nexus.admin.budget:
    description: Inspecter les budgets des arènes.
    default: op
  nexus.admin.player.export:
    description: Exporter les données d'un joueur.
    default: op
  nexus.admin.player.import:
    description: Importer les données d'un joueur.
    default: op
  nexus.admin.*:
    description: Accès complet aux commandes d'administration Nexus.
    default: op
    children:
      nexus.admin.reload: true
      nexus.admin.dump: true
      nexus.admin.budget: true
      nexus.admin.player.export: true
      nexus.admin.player.import: true
  nexus.holo.manage:
    description: Gérer les hologrammes Nexus via /nexus holo.
    default: op
  nexus.holo.view.default:
    description: Voir les hologrammes du groupe default.
    default: true
  nexus.holo.view.*:
    description: Voir tous les hologrammes, indépendamment du groupe.
    default: op
