name: HikaBrain
main: com.example.hikabrain.HikaBrainPlugin
version: 1.5.6
api-version: "1.21"
description: Hikabrain minigame for Spigot/Paper 1.21

commands:
  hb:
    description: Commande principale HikaBrain
    usage: "/hb help"
    aliases: [hikabrain]

permissions:
  hikabrain.admin:
    description: Accès aux commandes d’administration HikaBrain
    default: op
