name: Nexus
version: ${project.version}
main: fr.heneria.nexus.Nexus
api-version: '1.21'
author: Projet Heneria
description: Plugin principal pour le mode de jeu Nexus sur le serveur Heneria.
softdepend: [PlaceholderAPI]
commands:
  nx:
    description: Centre de contrôle de Nexus
    usage: /nx
    permission: nexus.admin
permissions:
  nexus.admin:
    description: Accès à l'administration de Nexus
    default: op
